#!/usr/bin/env python3
"""
Convert a fixed LIBERO subset manifest into a DreamZero-compatible LeRobot dataset.

This converter is designed for the "fixed small subset" stage:
- input episodes come from a manifest generated by build_libero_subset_manifest.py
- observations are taken from successful LIBERO demos
- action supervision is exported in DreamZero's single-arm joint-space layout

Important action design choice:
- action.joint_position stores the next-step absolute joint positions
- action.gripper_position stores the next-step absolute gripper position

DreamZero's relative-action path will subtract the chunk anchor state during
training, producing the future joint-space displacement targets used by the
policy head.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import av
import cv2
import h5py
import numpy as np
import pandas as pd
import torch

from groot.vla.data.dataset.lerobot import calculate_dataset_statistics


VIDEO_KEYS = [
    "observation.images.exterior_image_1_left",
    "observation.images.exterior_image_2_left",
    "observation.images.wrist_image_left",
]


def patch_torch_load_weights_only() -> None:
    original_load = torch.load

    def compat_load(*args, **kwargs):
        kwargs.setdefault("weights_only", False)
        return original_load(*args, **kwargs)

    torch.load = compat_load


def encode_video(frames: np.ndarray, output_path: Path, fps: int) -> None:
    options = {
        "threads": "1",
        "thread_type": "slice",
        "preset": "ultrafast",
        "tune": "zerolatency",
        "crf": "23",
    }

    container = av.open(str(output_path), mode="w")
    stream = container.add_stream("h264", rate=fps, options=options)
    stream.width = int(frames.shape[2])
    stream.height = int(frames.shape[1])
    stream.pix_fmt = "yuv420p"

    video_frame = av.VideoFrame(width=stream.width, height=stream.height, format="rgb24")
    frame_array = video_frame.to_ndarray(format="rgb24")

    for frame in frames:
        frame_array[:] = frame
        packet = stream.encode(video_frame)
        container.mux(packet)

    packet = stream.encode(None)
    container.mux(packet)
    container.close()


def resize_rgb_frames(frames: np.ndarray, width: int, height: int) -> np.ndarray:
    return np.stack([cv2.resize(frame, (width, height), interpolation=cv2.INTER_LINEAR) for frame in frames])


def build_state_and_action(
    joint_states: np.ndarray,
    gripper_states: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Build DreamZero-compatible state/action vectors.

    state  (14 dims): cartesian_position(6, zeros) + gripper_position(1) + joint_position(7)
    action (28 dims): cartesian_position(6, zeros)
                       cartesian_velocity(6, zeros)
                       gripper_position(1, next absolute)
                       gripper_velocity(1, next-current)
                       joint_position(7, next absolute)
                       joint_velocity(7, next-current)
    """
    T = int(joint_states.shape[0])
    gripper_scalar = gripper_states[:, :1].astype(np.float32)
    zeros_cart = np.zeros((T, 6), dtype=np.float32)

    state = np.concatenate(
        [zeros_cart, gripper_scalar, joint_states.astype(np.float32)],
        axis=1,
    )

    next_joint = np.concatenate([joint_states[1:], joint_states[-1:]], axis=0).astype(np.float32)
    next_gripper = np.concatenate([gripper_scalar[1:], gripper_scalar[-1:]], axis=0).astype(np.float32)
    joint_velocity = next_joint - joint_states.astype(np.float32)
    gripper_velocity = next_gripper - gripper_scalar

    action = np.concatenate(
        [
            zeros_cart,
            zeros_cart,
            next_gripper,
            gripper_velocity,
            next_joint,
            joint_velocity,
        ],
        axis=1,
    )
    return state, action


def write_meta_files(
    output_dir: Path,
    episodes_meta: list[dict[str, Any]],
    task_to_idx: dict[str, int],
    fps: int,
) -> None:
    meta_dir = output_dir / "meta"
    meta_dir.mkdir(parents=True, exist_ok=True)

    with open(meta_dir / "tasks.jsonl", "w") as f:
        for task, task_idx in sorted(task_to_idx.items(), key=lambda kv: kv[1]):
            f.write(json.dumps({"task_index": int(task_idx), "task": task}, ensure_ascii=False) + "\n")

    with open(meta_dir / "episodes.jsonl", "w") as f:
        for rec in episodes_meta:
            f.write(
                json.dumps(
                    {
                        "episode_index": rec["episode_index"],
                        "tasks": rec["tasks"],
                        "length": rec["length"],
                        "success": rec["success"],
                        "task_id": rec["task_id"],
                        "init_state_id": rec["init_state_id"],
                        "demo_key": rec["demo_key"],
                    },
                    ensure_ascii=False,
                )
                + "\n"
            )

    modality = {
        "state": {
            "cartesian_position": {"start": 0, "end": 6},
            "gripper_position": {"start": 6, "end": 7},
            "joint_position": {"start": 7, "end": 14},
        },
        "action": {
            "cartesian_position": {"start": 0, "end": 6},
            "cartesian_velocity": {"start": 6, "end": 12},
            "gripper_position": {"start": 12, "end": 13},
            "gripper_velocity": {"start": 13, "end": 14},
            "joint_position": {"start": 14, "end": 21},
            "joint_velocity": {"start": 21, "end": 28},
        },
        "video": {
            "exterior_image_1_left": {"original_key": "observation.images.exterior_image_1_left"},
            "exterior_image_2_left": {"original_key": "observation.images.exterior_image_2_left"},
            "wrist_image_left": {"original_key": "observation.images.wrist_image_left"},
        },
        "annotation": {
            "language.language_instruction": {},
            "language.language_instruction_2": {},
            "language.language_instruction_3": {},
        },
    }
    with open(meta_dir / "modality.json", "w") as f:
        json.dump(modality, f, indent=2, ensure_ascii=False)

    info = {
        "codebase_version": "v2.0",
        "robot_type": "libero_single_arm",
        "total_episodes": len(episodes_meta),
        "total_frames": int(sum(x["length"] for x in episodes_meta)),
        "total_tasks": len(task_to_idx),
        "total_videos": 3,
        "total_chunks": int(np.ceil(len(episodes_meta) / 1000)),
        "chunks_size": 1000,
        "fps": int(fps),
        "splits": {"train": "0:100"},
        "data_path": "data/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.parquet",
        "video_path": "videos/chunk-{episode_chunk:03d}/{video_key}/episode_{episode_index:06d}.mp4",
        "features": {
            "observation.images.exterior_image_1_left": {
                "dtype": "video",
                "shape": [180, 320, 3],
                "names": ["height", "width", "channel"],
                "video_info": {
                    "video.fps": int(fps),
                    "video.codec": "h264",
                    "video.pix_fmt": "yuv420p",
                    "video.is_depth_map": False,
                    "has_audio": False,
                },
            },
            "observation.images.exterior_image_2_left": {
                "dtype": "video",
                "shape": [180, 320, 3],
                "names": ["height", "width", "channel"],
                "video_info": {
                    "video.fps": int(fps),
                    "video.codec": "h264",
                    "video.pix_fmt": "yuv420p",
                    "video.is_depth_map": False,
                    "has_audio": False,
                },
            },
            "observation.images.wrist_image_left": {
                "dtype": "video",
                "shape": [180, 320, 3],
                "names": ["height", "width", "channel"],
                "video_info": {
                    "video.fps": int(fps),
                    "video.codec": "h264",
                    "video.pix_fmt": "yuv420p",
                    "video.is_depth_map": False,
                    "has_audio": False,
                },
            },
            "observation.state": {"dtype": "float64", "shape": [14], "names": ["cartesian_position", "gripper_position", "joint_position"]},
            "action": {
                "dtype": "float64",
                "shape": [28],
                "names": [
                    "cartesian_position",
                    "cartesian_velocity",
                    "gripper_position",
                    "gripper_velocity",
                    "joint_position",
                    "joint_velocity",
                ],
            },
            "timestamp": {"dtype": "float64", "shape": [1]},
            "task_index": {"dtype": "int64", "shape": [1]},
            "episode_index": {"dtype": "int64", "shape": [1]},
            "index": {"dtype": "int64", "shape": [1]},
            "next.reward": {"dtype": "float64", "shape": [1]},
            "next.done": {"dtype": "bool", "shape": [1]},
            "is_terminal": {"dtype": "bool", "shape": [1]},
            "is_first": {"dtype": "bool", "shape": [1]},
            "discount": {"dtype": "float64", "shape": [1]},
            "annotation.language.language_instruction": {"dtype": "int64", "shape": [1]},
            "annotation.language.language_instruction_2": {"dtype": "int64", "shape": [1]},
            "annotation.language.language_instruction_3": {"dtype": "int64", "shape": [1]},
        },
    }
    with open(meta_dir / "info.json", "w") as f:
        json.dump(info, f, indent=2, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert a fixed LIBERO subset manifest into LeRobot format")
    parser.add_argument("--manifest", type=str, required=True, help="Subset manifest JSON generated by build_libero_subset_manifest.py")
    parser.add_argument("--output-dir", type=str, required=True, help="Destination LeRobot dataset directory")
    parser.add_argument("--fps", type=int, default=5, help="Video FPS to write into the converted subset")
    parser.add_argument("--image-width", type=int, default=320, help="Output image width")
    parser.add_argument("--image-height", type=int, default=180, help="Output image height")
    args = parser.parse_args()

    patch_torch_load_weights_only()

    from libero.libero import benchmark, get_libero_path

    manifest_path = Path(args.manifest)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    with open(manifest_path) as f:
        manifest = json.load(f)

    suite = str(manifest["suite"])
    benchmark_dict = benchmark.get_benchmark_dict()
    suite_key = suite.lower()
    if suite_key in benchmark_dict:
        task_suite = benchmark_dict[suite_key]()
    elif hasattr(benchmark, "task_maps") and suite_key in benchmark.task_maps:
        task_suite = benchmark.Benchmark()
        task_suite.name = suite_key
        task_suite._make_benchmark()
    else:
        raise ValueError(f"Unknown LIBERO suite: {suite}")

    task_to_idx = {"not provided": 0}
    episodes_meta: list[dict[str, Any]] = []

    for episode_index, episode in enumerate(manifest["episodes"]):
        task_id = int(episode["task_id"])
        init_state_id = int(episode["init_state_id"])
        task_instruction = str(episode["language_instruction"])
        if task_instruction not in task_to_idx:
            task_to_idx[task_instruction] = len(task_to_idx)
        task_index = task_to_idx[task_instruction]

        task = task_suite.get_task(task_id)
        rel_demo = task_suite.get_task_demonstration(task_id)
        demo_path = Path(get_libero_path("datasets")) / rel_demo
        demo_key = f"demo_{init_state_id}"
        if not demo_path.exists():
            raise FileNotFoundError(f"Missing LIBERO demo file: {demo_path}")

        with h5py.File(demo_path, "r") as f:
            if demo_key not in f["data"]:
                raise KeyError(f"Demo key {demo_key} not found in {demo_path}")
            demo = f["data"][demo_key]
            obs = demo["obs"]
            joint_states = np.asarray(obs["joint_states"], dtype=np.float32)
            gripper_states = np.asarray(obs["gripper_states"], dtype=np.float32)
            agentview = resize_rgb_frames(np.asarray(obs["agentview_rgb"]), args.image_width, args.image_height)
            wrist = resize_rgb_frames(np.asarray(obs["eye_in_hand_rgb"]), args.image_width, args.image_height)
            exterior_1 = agentview
            exterior_2 = agentview.copy()

        state, action = build_state_and_action(joint_states, gripper_states)
        T = int(state.shape[0])
        rewards = np.zeros((T,), dtype=np.float32)
        rewards[-1] = 1.0
        done = np.zeros((T,), dtype=bool)
        done[-1] = True
        first = np.zeros((T,), dtype=bool)
        first[0] = True
        discount = np.ones((T,), dtype=np.float32)

        episode_chunk = episode_index // 1000
        data_dir = output_dir / f"data/chunk-{episode_chunk:03d}"
        data_dir.mkdir(parents=True, exist_ok=True)
        for video_key in VIDEO_KEYS:
            (output_dir / f"videos/chunk-{episode_chunk:03d}/{video_key}").mkdir(parents=True, exist_ok=True)

        parquet_path = data_dir / f"episode_{episode_index:06d}.parquet"
        df = pd.DataFrame(
            {
                "observation.state": [row.astype(np.float64) for row in state],
                "action": [row.astype(np.float64) for row in action],
                "next.reward": rewards.astype(np.float64),
                "next.done": done,
                "is_terminal": done.copy(),
                "is_first": first,
                "discount": discount.astype(np.float64),
                "timestamp": np.arange(T, dtype=np.float64) / float(args.fps),
                "task_index": np.full(T, task_index, dtype=np.int64),
                "episode_index": np.full(T, episode_index, dtype=np.int64),
                "frame_index": np.arange(T, dtype=np.int64),
                "index": np.arange(T, dtype=np.int64),
                "annotation.language.language_instruction": np.full(T, task_index, dtype=np.int64),
                "annotation.language.language_instruction_2": np.zeros(T, dtype=np.int64),
                "annotation.language.language_instruction_3": np.zeros(T, dtype=np.int64),
            }
        )
        df.to_parquet(parquet_path, index=False)

        encode_video(
            exterior_1,
            output_dir / f"videos/chunk-{episode_chunk:03d}/observation.images.exterior_image_1_left/episode_{episode_index:06d}.mp4",
            fps=args.fps,
        )
        encode_video(
            exterior_2,
            output_dir / f"videos/chunk-{episode_chunk:03d}/observation.images.exterior_image_2_left/episode_{episode_index:06d}.mp4",
            fps=args.fps,
        )
        encode_video(
            wrist,
            output_dir / f"videos/chunk-{episode_chunk:03d}/observation.images.wrist_image_left/episode_{episode_index:06d}.mp4",
            fps=args.fps,
        )

        episodes_meta.append(
            {
                "episode_index": int(episode_index),
                "task_id": task_id,
                "init_state_id": init_state_id,
                "demo_key": demo_key,
                "tasks": [task_instruction],
                "length": T,
                "success": True,
            }
        )

    write_meta_files(output_dir, episodes_meta, task_to_idx, fps=args.fps)

    parquet_files = sorted((output_dir / "data").glob("chunk-*/*.parquet"))
    stats = calculate_dataset_statistics(
        parquet_files,
        features=["observation.state", "action", "next.reward", "discount", "timestamp"],
    )
    stats_serialized = {k: v.model_dump(mode="json") for k, v in stats.items()}
    stats_serialized["num_trajectories"] = len(episodes_meta)
    stats_serialized["total_trajectory_length"] = int(sum(x["length"] for x in episodes_meta))
    with open(output_dir / "meta/stats.json", "w") as f:
        json.dump(stats_serialized, f, indent=2, ensure_ascii=False)

    print(
        json.dumps(
            {
                "output_dir": str(output_dir),
                "num_episodes": len(episodes_meta),
                "num_tasks": len(task_to_idx) - 1,
                "fps": int(args.fps),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
